name : barangay-management-system
on :
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs :
  test :
    runs-on : ubuntu-latest
    name : Run Laravel Test

    services :
      mysql :
        image : mysql:8.0
        env :
          MYSQL_DATABASE : test_db
          MYSQL_USER : root
          MYSQL_PASSWORD : ''
          MYSQL_ROOT_PASSWORD : ''
        ports :
          - 3306

    steps :
      - name: checkout
        uses: actions/checkout@v4
      - name: setup php
        uses: shivammathur/setup-php@v2
        with :
          php-version : '8.2'
      - name : nodejs
        uses : actions/setup-node@v4
        with :
          node-version : '20'


      - name : install dependencies
        run : |
          composer install --no-interaction --prefer-dist
          npm install

      - name: migrate database
        env :
          DB_CONNECTION : mysql
          DB_HOST : 127.0.0.1
          DB_PORT : 3306
          DB_DATABASE : test_db
          DB_USERNAME : root
          DB_PASSWORD : ''
        run : |
          php artisan migrate --no-interaction
