name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo_mysql, intl


      - name: node js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install Dependencies
        run: |
          composer install --no-interaction --prefer-dist

      - name: setup env
        run: |
          cp .env.example .env

      - name: Install NPM Dependencies
        run: |
          npm install

      - name: Build Assets
        run: |
          npm run build

      - name: generate App Key
        run: |
          php artisan key:generate

      - name: database sqlite
        run: |
          touch database/database.sqlite


      - name: Migrate Database
        run: |
          php artisan migrate --seed


      - name: Clear Cache
        run: |
          php artisan cache:clear
          php artisan config:clear
          php artisan route:clear
          php artisan view:clear

      - name: Deploy to Hostinger
        uses: easingthemes/ssh-deploy@main
        with:
          SOURCE: "."
          SSH_PRIVATE_KEY: ${{ secrets.HOSTINGER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOSTINGER_SSH_HOST }}
          REMOTE_USER: ${{ secrets.HOSTINGER_SSH_USER }}
          REMOTE_PORT: ${{ secrets.HOSTINGER_SSH_PORT }}
          TARGET: ${{ secrets.HOSTINGER_SSH_TARGET_PATH }}


          SCRIPT_BEFORE: |
            ls -a

          EXCLUDE: "/node_modules, /vendor, /storage, /bootstrap/cache, /public/storage, /env, /.github"




